import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        pages
        <a href="/home">home</a>
        <a href="/courses/y2/fall/stats_3y03/lecture_notes/13_-_continuous_random_variable">
          ajksdhfk
        </a>
        <a href="/courses/y3/3sh3"></a>
      </main>
    </>
  );
}
